import Footer from "./Footer";
import Header from "./Header";
import MenuPrincipal from "./MenuPrincipal";
import "./globals.css";

export const metadata = {
  title: "Feria Inmobiliaria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Header />
      <MenuPrincipal />
      <div className="">{children}</div>

      <Footer />
    </html>
  );
}
